service: serverless-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    variable1: value1


functions:
  example:
    handler: handler.example
    events:
      - httpApi:
          path: /
          method: get
