on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Lambda Deployment
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm install -g serverless
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: serverless deploy -v
